Test new stuff

diff --git a/.github/workflows/github.yml b/.github/workflows/github.yml
--- a/.github/workflows/github.yml
+++ b/.github/workflows/github.yml
@@ -2,89 +2,65 @@ name: Build & Test Agora
 on: [push, pull_request]
 
 jobs:
-  mac_build:
-    name: Build & Run test-suite on Mac OS
-    strategy:
-        matrix:
-            os: [macOS-10.14]
-            # dc: [dmd-2.088.1, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]
-            dc: [dmd-2.086.1]
+
+  # Fails, linker error with sqlite3..
+  ########################################################################
+  # mac_build:
+  #   name: Build & Run test-suite on Mac OS
+  #   strategy:
+  #       matrix:
+  #           os: [macOS-10.14]
+  #           # dc: [dmd-2.088.1, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]
+  #           dc: [dmd-2.086.1]
+  #   runs-on: macOS-10.14
+  #   steps:
+  #   - uses: actions/checkout@v1
+  #     with:
+  #       submodules: true
+  #   - name: Prepare compiler
+  #     uses: mihails-strasuns/setup-dlang@v0.3.0
+  #     with:
+  #         compiler: ${{ matrix.dc }}
+  #   - name: Build and test agora
+  #     run: |
+  #       brew install sqlite3
+  #       ./ci/travis_osx_setup.sh
+  #       set -xeu
+  #       set -o pipefail
+  #       export PATH="${PATH-}:$HOME/bin/"
+  #       export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
+  #       export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
+  #       dub test -b unittest-cov --skip-registry=all --compiler=dmd
+  #       rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
+  #       dub build --skip-registry=all --compiler=dmd
+  ########################################################################
+
+  test_mac:
     runs-on: macOS-10.14
     steps:
     - uses: actions/checkout@v1
       with:
         submodules: true
-    - name: Prepare compiler
-      uses: mihails-strasuns/setup-dlang@v0.3.0
-      with:
-          compiler: ${{ matrix.dc }}
+    - name: Install D and Dub
+      run: |
+        brew install dmd
+        brew install dub
+        brew install sqlite3
     - name: Build and test agora
       run: |
-        brew install sqlite3
-        ./ci/travis_osx_setup.sh
-        set -xeu
-        set -o pipefail
-        export PATH="${PATH-}:$HOME/bin/"
-        export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
-        export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
-        dub test -b unittest-cov --skip-registry=all --compiler=dmd
-        rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
-        dub build --skip-registry=all --compiler=dmd
+        ./ci/github_mac_setup.sh
+        ./ci/run.sh
 
-# jobs:
-#     mac_build:
-#         name: Build & Run test-suite on Mac OS
-#         strategy:
-#             matrix:
-#                 os: [macOS-10.14]
-#                 # dc: [dmd-2.088.1, dmd-2.087.1, ldc-1.17.0, ldc-1.16.0, dmd-master, ldc-master]
-#                 dc: [dmd-2.087.1]
+# set -xeu
+# set -o pipefail
+# export PATH="${PATH-}:$HOME/bin/"
+# export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
+# export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
+# dub test -b unittest-cov --skip-registry=all --compiler=dmd
+# rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
+# dub build --skip-registry=all --compiler=dmd
 
-#         runs-on: ${{ matrix.os }}
-#         steps:
-#             - uses: actions/checkout@v1
-#               with:
-#                 submodules: true
-#             - name: Prepare compiler
-#               uses: mihails-strasuns/setup-dlang@v0.3.0
-#               with:
-#                   compiler: ${{ matrix.dc }}
-#             - name: Install D and Dub
-#               run: |
-#                 brew install sqlite3
-#             - name: Run test-suite & build Agora
-#               run: |
-#                 ./ci/travis_osx_setup.sh
-#                 set -xeu
-#                 set -o pipefail
-#                 export PATH="${PATH-}:$HOME/bin/"
-#                 export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
-#                 export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
-#                 dub test -b unittest-cov --skip-registry=all --compiler=dmd
-#                 rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
-#                 dub build --skip-registry=all --compiler=dmd
-
-              # run: |
-              #   ./ci/github_mac_setup.sh
-              #   ./ci/run.sh
-
-    # - name: Install D and Dub
-    #   run: |
-    #     brew install dmd
-    #     brew install dub
-    #     brew install sqlite3
-    # - name: Build and test agora
-    #   run: |
-    #     ./ci/travis_osx_setup.sh
-    #     set -xeu
-    #     set -o pipefail
-    #     export PATH="${PATH-}:$HOME/bin/"
-    #     export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
-    #     export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
-    #     dub test -b unittest-cov --skip-registry=all --compiler=dmd
-    #     rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
-    #     dub build --skip-registry=all --compiler=dmd
-
+# Works on Linux:
     # linux_build:
     #     name: Build & Run test-suite on Linux
     #     strategy:
@@ -106,37 +82,3 @@ jobs:
     #           run: |
     #             ./ci/github_linux_setup.sh
     #             ./ci/run.sh
-
-# ##################################
-# name: Test builds on multiple OSes
-
-# on:
-#   push:
-#     branches:
-#       - v0.x.x
-
-# jobs:
-#   test_mac:
-#     # runs-on: macOS-latest
-#     runs-on: macOS-10.14
-#     steps:
-#     - uses: actions/checkout@v1
-#       with:
-#         submodules: true
-#     - name: Install D and Dub
-#       run: |
-#         brew install dmd
-#         brew install dub
-#         brew install sqlite3
-#     - name: Build and test agora
-#       run: |
-#         ./ci/travis_osx_setup.sh
-#         set -xeu
-#         set -o pipefail
-#         export PATH="${PATH-}:$HOME/bin/"
-#         export LIBRARY_PATH="${LD_LIBRARY_PATH-}:/usr/local/lib/"
-#         export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"
-#         dub test -b unittest-cov --skip-registry=all --compiler=dmd
-#         rdmd --compiler=dmd ./tests/runner.d --compiler=dmd -cov
-#         dub build --skip-registry=all --compiler=dmd
-# ##################################
